version: '3'
services:
  ubuntu:
    build: ./ubuntu
    restart: 'no'
    ports:
      - '3000:80'
    volumes:
      - '../:/var/www/html'
      - './php/php.ini:/etc/php/7.2/apache2/php.ini'
      - './php/php.ini:/etc/php/7.2/cli/php.ini'
    links:
      - mysql
  mysql:
    image: 'mysql:5.7'
    restart: 'no'
    command: '--sql_mode=""'
    ports:
      - '3306:3306'
    volumes:
      - './mysql/data:/var/lib/mysql'
      - './mysql/logs:/var/log/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: 'no'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '5000:80'
    volumes:
      - /sessions
